// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPi9Ejp89E5c5lFOAatNYtC09Yh535vBU',
    appId: '1:966581707901:web:92b90493b53ccb641d7d14',
    messagingSenderId: '966581707901',
    projectId: 'spoilt-18e2a',
    authDomain: 'spoilt-18e2a.firebaseapp.com',
    storageBucket: 'spoilt-18e2a.appspot.com',
    measurementId: 'G-QSYHYDNR1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvuE2MoeyRhOYr9x8uAY9ueuOMK7VDAgs',
    appId: '1:966581707901:android:f01235ded57eaa941d7d14',
    messagingSenderId: '966581707901',
    projectId: 'spoilt-18e2a',
    storageBucket: 'spoilt-18e2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCytVgRZWHjGXK9jCABXo715XDYzTGAWZI',
    appId: '1:966581707901:ios:f136eb388e5fb4c31d7d14',
    messagingSenderId: '966581707901',
    projectId: 'spoilt-18e2a',
    storageBucket: 'spoilt-18e2a.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCytVgRZWHjGXK9jCABXo715XDYzTGAWZI',
    appId: '1:966581707901:ios:4b9253c580451d2b1d7d14',
    messagingSenderId: '966581707901',
    projectId: 'spoilt-18e2a',
    storageBucket: 'spoilt-18e2a.appspot.com',
    iosBundleId: 'com.example.fyp.RunnerTests',
  );
}
